### PR TITLE
BaseMixin domain intervention support with decoders

### PR DESCRIPTION
**Pull request by kclary**
Starting a discussion about adding the features on this branch to master/main (#178). `domains-amidar` is a branch off `domains`, we can start with a pull request into that branch if that's a better first step. 

I've updated some BaseMixins in Amidar. It's not clear which pieces are *needed* for all games. Is there an object-based test we can apply?

### CODE REVIEW

**Comment by kclary** [comment]
Travis check.sh failed: 
> ImportError: cannot import name 'AbstractContextManager'

AbstractContextManager was added in Python 3.6 - will need to update Travis build

**Comment by kclary** [comment]
On tests for the BaseMixins - How do you know when to add a `decode`, `__repr__`, `__str__` method to a BaseMixins object vs when the context manager will do its magic without help? Maybe that is what #152 is asking?

**Comment by kclary** [comment]
gh-actions CI failed due to #174. I don't understand this error, looks like the unit tests passed?

**Comment by kclary** [comment]
gh-actions build is crying somewhere and won't say what is wrong

**Comment by jjfiv** [comment]
I can't find any info anywhere, but maybe we ran out of free hours? We had a bunch that ran until the 6-hour limit hit...

**Comment by kclary** [comment]
@jjfiv is ok to merge, we'll see if that helps actions come back to us
